PackageIdentifier: YuanGui.PDFHelper
PackageVersion: 1.2.1
Installers:
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://www.ailocal.com.cn/download/YLPDF_v1.2.1.exe
  InstallerSha256: 356eba2b2b949441235520db796223fc42d7d61ca920b40d527567221835a799
  InstallerSwitches:
    Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
    SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
    InstallLocation: /DIR="<INSTALLPATH>"
  InstallModes:
  - silent
  - silentWithProgress
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.6.0
