PackageIdentifier: YuanGui.VideoHelper
PackageVersion: 1.0.0
Installers:
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://www.ailocal.com.cn/download/YLVideo_v1.0.exe
  InstallerSha256: fadf6290c96e7945fca511ca2d2711e30ad9e48ea7c6c85f669cd3c370bf4314
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  UpgradeBehavior: uninstallPrevious
ManifestType: installer
ManifestVersion: 1.6.0
