PackageIdentifier: YuanGui.PhotoHelper
PackageVersion: 1.0.1
Installers:
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://www.ailocal.com.cn/download/YLPhoto_v1.0.1.exe
  InstallerSha256: c4c5d4023302052c1d8f128ad5a20dfbc2fcfc54d2d96d0368bc7200e2f0a001
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  UpgradeBehavior: uninstallPrevious
ManifestType: installer
ManifestVersion: 1.6.0
